### ISSUE TITLE
Add custom tariff for comparison

### ISSUE THREAD

**Issue by BenjaminEHowe** [ndg63276/octopus#1]
I'd like to be able to add a custom tariff (i.e. an arbitrary unit cost and daily standing charge) for comparison with Octopus Agile.

**Comment by ndg63276** [comment]
Should be live now (might need a couple of refreshes), let me know if it works for you!

**Comment by BenjaminEHowe** [comment]
This works brilliantly now, thank you. I have an "exclusive octopus" tariff and I can see that I could save a few pennies by switching to agile octopus. I definitely owe you a beer / hot chocolate / etc.
